### ISSUE TITLE
Build failed caused by the file numbering >=10

### ISSUE THREAD

**Issue by visualDust** [visualDust/ml.akasaki.space#31]
github actions build failed caused by files naming with the prefix of number bigger 10.
```
TypeError: Cannot read property '1' of null
    at readMDFileTitle (/home/runner/work/ml.akasaki.space/ml.akasaki.space/js/utils.js:37:62)
    at /home/runner/work/ml.akasaki.space/ml.akasaki.space/js/utils.js:27:27
    at Array.map (<anonymous>)
    at getSidebar (/home/runner/work/ml.akasaki.space/ml.akasaki.space/js/utils.js:26:10)
    at Object.<anonymous> (/home/runner/work/ml.akasaki.space/ml.akasaki.space/docs/.vuepress/config.js:49:31)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at loadConfig (/home/runner/work/ml.akasaki.space/ml.akasaki.space/node_modules/@vuepress/core/lib/node/loadConfig.js:31:18)
    at App.resolveConfigAndInitialize (/home/runner/work/ml.akasaki.space/ml.akasaki.space/node_modules/@vuepress/core/lib/node/App.js:64:24)
    at App.process (/home/runner/work/ml.akasaki.space/ml.akasaki.space/node_modules/@vuepress/core/lib/node/App.js:103:16)
    at build (/home/runner/work/ml.akasaki.space/ml.akasaki.space/node_modules/@vuepress/core/lib/index.js:26:13)
    at /home/runner/work/ml.akasaki.space/ml.akasaki.space/node_modules/vuepress/lib/util.js:35:12
```

**Comment by visualDust** [comment]
新的问题来了，文章排序挂了（指sort那一行
它排出来的是 1 11 12 13 2 3 4 5
![@J~M08H7}@YVYWBSGQPG7GX](https://user-images.githubusercontent.com/33346934/117304965-e5559380-aeb0-11eb-8125-b6b60a091745.jpg)

**Comment by visualDust** [comment]
@Therainisme 出来看笑话

**Comment by Therainisme** [comment]
lideming快改

**Comment by visualDust** [comment]
#32 resolved this

**Comment by visualDust** [comment]
好极了，又坏了

**Comment by visualDust** [comment]
#33 fixed
